[package]
name = "falcon-bms-callbacker"
version = "0.2.0"
edition = "2024"
build = "build.rs"

[build-dependencies]
vergen-git2 = { version = "1.0.0", features = ["build", "cargo", "rustc", "si"] }
anyhow = "*"

[[bin]]
name = "falcon_bms_callbacker"
path = "src/main.rs"

[dependencies]
bms-sm = { git = "https://github.com/kungfoo/bms-rs.git", version = "0.2" }
falcon-key-file = { git = "https://github.com/kungfoo/falcon-bms-keyfile.git", version = "0.3.0" }
tokio = { version = "1", features = ["full"] }
log = "0.4"
env_logger = "0.11"
winapi = "*"
user32-sys = "*"
enigo = "0.6.1"
seahash = "4.1.0"
levenshtein = "1.0.5"
config = { version = "0.15", features = ["toml"] }

windows = { version = "0.62.0", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Input_KeyboardAndMouse",
] }

[profile.release]
strip = true  # Automatically strip symbols from the binary.
opt-level = "z"  # Optimize for size.
lto = true
