name: Run cargo build and test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        submodules: recursive
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  package:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        submodules: recursive
    - name: Build for x64
      run: cargo build --verbose --release --target=x86_64-pc-windows-gnu
    - name: Build for i686
      run: cargo build --verbose --release --target=stable-i686-pc-windows-gnu
