name: Run tests and build a package

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        submodules: recursive
    - name: Run tests
      run: cargo test --verbose

  build_release_and_package:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        submodules: recursive
    - name: Build for x64
      run: cargo build --release --target=x86_64-pc-windows-gnu
    - name: Build for i686
      run: rustup target add i686-pc-windows-msvc && cargo build --release --target=i686-pc-windows-msvc
